[alembic]
script_location = .
prepend_sys_path = .
version_path_separator = os
sqlalchemy.url = postgresql://recipe_user:recipe_password@localhost:5432/recipe_db

[post_write_hooks]
hooks = black
black.type = console_scripts
black.entrypoint = black
black.options = -l 88
